name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build BeatSaberAvatar.js
        run: |
          npm ci
          mkdir dist
          npm run build
          git add --force dist/BeatSaberAvatar.js
          git status

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: .
          clean: false
          single-commit: true
